/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import javax.swing.JOptionPane;
import DTO.MateriaisDTO;
import DAO.MateriaisDAO;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.util.List;


public class TelaMateriaisView extends javax.swing.JFrame {

    /**
     * Creates new form TelaMateriaisView
     */
    public TelaMateriaisView() {
        initComponents();
        setLocationRelativeTo(null);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        VoltarTelaMateriais = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaListaMateriais = new javax.swing.JTable();
        NovoMaterialBtn = new javax.swing.JButton();
        ConsultaMateriaisBtn = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        BtnApagar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Materiais");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        VoltarTelaMateriais.setBackground(new java.awt.Color(153, 153, 153));
        VoltarTelaMateriais.setText("Voltar");
        VoltarTelaMateriais.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VoltarTelaMateriais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarTelaMateriaisActionPerformed(evt);
            }
        });

        TabelaListaMateriais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código Item", "Nome Item", "Unidade de Medida"
            }
        ));
        jScrollPane1.setViewportView(TabelaListaMateriais);

        NovoMaterialBtn.setBackground(new java.awt.Color(102, 204, 255));
        NovoMaterialBtn.setText("Cadastrar Novo Material");
        NovoMaterialBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoMaterialBtnActionPerformed(evt);
            }
        });

        ConsultaMateriaisBtn.setBackground(new java.awt.Color(102, 204, 255));
        ConsultaMateriaisBtn.setText("Consultar");
        ConsultaMateriaisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaMateriaisBtnActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Lapis-icon.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        BtnApagar.setBackground(new java.awt.Color(255, 0, 0));
        BtnApagar.setForeground(new java.awt.Color(255, 255, 255));
        BtnApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/54324.png"))); // NOI18N
        BtnApagar.setBorder(null);
        BtnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnApagarActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pref png1.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NovoMaterialBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ConsultaMateriaisBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                            .addComponent(BtnApagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(VoltarTelaMateriais, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(355, 355, 355))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(203, 203, 203))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jButton3)
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConsultaMateriaisBtn)
                    .addComponent(NovoMaterialBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(BtnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addComponent(VoltarTelaMateriais)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarTelaMateriaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarTelaMateriaisActionPerformed
        TelaMenuView telaMenu = new TelaMenuView();
        telaMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VoltarTelaMateriaisActionPerformed

    private void NovoMaterialBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoMaterialBtnActionPerformed
        TelaCadastroMaterial telaNovoMaterial = new TelaCadastroMaterial();
        telaNovoMaterial.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NovoMaterialBtnActionPerformed

    private void ConsultaMateriaisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaMateriaisBtnActionPerformed
        try{
            listarValores();
        } catch(Exception erro){
            System.out.println("Tela Materiais try/catch" + erro);
        }
    }//GEN-LAST:event_ConsultaMateriaisBtnActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int linhaSelecionada = TabelaListaMateriais.getSelectedRow();
        if (linhaSelecionada != -1) {
            // Recuperar dados da linha selecionada

            String CódigoItem = (String) TabelaListaMateriais.getValueAt(linhaSelecionada, 0);
            String NomeItem = (String) TabelaListaMateriais.getValueAt(linhaSelecionada, 1);
            String UniMedida = (String) TabelaListaMateriais.getValueAt(linhaSelecionada, 2);
            

            // Obter novos valores

            String novaCódigoItem = JOptionPane.showInputDialog("Código do Item:", CódigoItem);
            String novaNomeItem = JOptionPane.showInputDialog("Nome do Item:", NomeItem);
            String novaUniMedida = JOptionPane.showInputDialog("Unidade de Medida:", UniMedida);
            

            // Chamar método para editar no banco de dados
            editarNoBanco( CódigoItem, novaCódigoItem, novaNomeItem, novaUniMedida);

            // Atualizar a linha na tabela

            TabelaListaMateriais.setValueAt(novaCódigoItem != null ? novaCódigoItem : CódigoItem, linhaSelecionada, 0);
            TabelaListaMateriais.setValueAt(novaNomeItem != null ? novaNomeItem : NomeItem, linhaSelecionada, 1);
            TabelaListaMateriais.setValueAt(novaUniMedida != null ? novaUniMedida : UniMedida, linhaSelecionada, 2);
            

        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha para editar.");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void BtnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnApagarActionPerformed
        int linhaSelecionada = TabelaListaMateriais.getSelectedRow();
        if (linhaSelecionada != -1) {
    int resposta = JOptionPane.showConfirmDialog(
        null,
        "Tem certeza que deseja apagar este item?",
        "Confirmação",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE
    );

    if (resposta == JOptionPane.YES_OPTION) {
        try {
            // Acessando as colunas corretas
            String CódigoItem = (String) TabelaListaMateriais.getValueAt(linhaSelecionada, 0); // N Medicao

            // Remover a linha do modelo
            ((DefaultTableModel) TabelaListaMateriais.getModel()).removeRow(linhaSelecionada);

            // Chamar método para remover do banco de dados
            removerDoBanco(CódigoItem);
        } catch (ArrayIndexOutOfBoundsException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao acessar os dados da tabela. Verifique os índices.");
            ex.printStackTrace();
        }
    } else {
        // O usuário escolheu não apagar
        JOptionPane.showMessageDialog(null, "Operação cancelada.");
    }
} else {
    JOptionPane.showMessageDialog(null, "Selecione uma linha para apagar.");
}
    }//GEN-LAST:event_BtnApagarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        TelaMenuView menu = new TelaMenuView();
       menu.setVisible(true);
       
       this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMateriaisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMateriaisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMateriaisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMateriaisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMateriaisView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnApagar;
    private javax.swing.JButton ConsultaMateriaisBtn;
    private javax.swing.JButton NovoMaterialBtn;
    private javax.swing.JTable TabelaListaMateriais;
    private javax.swing.JButton VoltarTelaMateriais;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

private void listarValores(){
    try{
        
        MateriaisDAO materiaisDao = new MateriaisDAO();
        DefaultTableModel model = (DefaultTableModel) TabelaListaMateriais.getModel();
                model.setNumRows(0);
                
                String CódigoItem = null;
                String NomeItem = null;

                String UniMedida = null;
                
                List<MateriaisDTO> lista = materiaisDao.consultarMateriais(CódigoItem, NomeItem, UniMedida);
                
                for (int i = 0; i < lista.size(); i++) {
                    
                    model.addRow(new Object[] {
                        lista.get(i).getCódigoItem(),
                        lista.get(i).getNomeItem(),
                        lista.get(i).getUniMedida()
                        ,});
                }
                } catch(Exception erro){
                    JOptionPane.showMessageDialog(null, "TelaMateriais" + erro);
    }
}
private void editarNoBanco(String codigoItemAntigo, String novoCodigoItem, String nomeItem, String uniMedida) {
    Connection conn = null;
    PreparedStatement stmt = null;

    try {
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetoestoque?serverTimezone=America/Sao_Paulo", "root", "1234");
        
        // Começa a construção da SQL
        StringBuilder sql = new StringBuilder("UPDATE projetoestoque.materiais_estoque SET ");
        List<String> updates = new ArrayList<>();

        // Adiciona apenas os campos que não são nulos
        if (novoCodigoItem != null) updates.add("CódigoItem = ?");
        if (nomeItem != null) updates.add("NomeItem = ?");
        if (uniMedida != null) updates.add("UniMedida = ?");
        
        // Verifica se algum campo foi passado para atualização
        if (updates.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nenhum campo para atualizar.");
            return;
        }

        // Adiciona os updates à SQL
        sql.append(String.join(", ", updates));
        sql.append(" WHERE CódigoItem = ?"); // Condições para identificar o registro

        stmt = conn.prepareStatement(sql.toString());

        // Preenche os parâmetros
        int index = 1;
        
        if (novoCodigoItem != null) stmt.setString(index++, novoCodigoItem);
        if (nomeItem != null) stmt.setString(index++, nomeItem);
        if (uniMedida != null) stmt.setString(index++, uniMedida);
        
        // Adiciona o parâmetro de filtro
        stmt.setString(index++, codigoItemAntigo); // Use o código antigo para a condição WHERE
        
        // Execute a atualização
        stmt.executeUpdate();
        JOptionPane.showMessageDialog(null, "Registro editado com sucesso!");
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Erro ao editar registro no banco.");
    } finally {
        try {
            if (stmt != null) stmt.close();
            if (conn != null) conn.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
}


private void removerDoBanco(String CódigoItem) {
        // Aqui você deve implementar a lógica para remover o registro do banco de dados
        Connection conn = null; // Obtenha sua conexão aqui
        PreparedStatement stmt = null;
        
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetoestoque?serverTimezone=America/Sao_Paulo", "root", "1234");
             System.out.println("Conexão estabelecida com sucesso!");// Ajuste conforme necessário
            
            
           String sql = "DELETE FROM projetoestoque.materiais_estoque WHERE CódigoItem = ?";
            stmt = conn.prepareStatement(sql);
            stmt.setString(1, CódigoItem);
            
            stmt.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao apagar registro do banco.");
        } finally {
            // Feche a conexão e o statement, se necessário
            try {
                if (stmt != null) stmt.close();
                if (conn != null) conn.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }

}

